sudo: required

services:
  - docker

before_install:
  - docker build -t brilliantassociates/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brilliantassociates/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-858193300132"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

 #+D6cQJo05aX8uazFpR5KQASUp/pZG1oAR25S/yDZ